[package]
name = "prisma-client-rust-cli"
version = "0.3.0"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
license = "MIT"

[[bin]]
name = "prisma-client-rust"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "0.2.4"
convert_case = "0.4.0"
syn = "1.0.86"
quote = "1.0.15"
directories = "4.0.1"
flate2 = "1.0.22"
reqwest = {version="0.11.9", features=["blocking"]}
serde_path_to_error = "0.1.7"