[package]
name = "prisma-client-rust-cli"
version = "0.4.1"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.5.0"
http = "0.2.6"
directories = "4.0.1"
flate2 = "1.0.23"
regex = "1.5.5"
serde_path_to_error = "0.1.7"
quote = "1.0.18"
reqwest = { version = "0.11.10", features = ["blocking"] }
syn = "1.0.91"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }